export const ON_LOGIN = 'ON_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// Capsules //
export const GET_ALL_CAPSULES = 'GET_ALL_CAPSULES';
export const GET_CAPSULES_SUCCESS = 'GET_CAPSULES_SUCCESS';
export const GET_CAPSULES_FAIL = 'GET_CAPSULES_FAIL';

export const GET_CAPSULES_DETAIL = 'GET_CAPSULES_DETAIL';
export const GET_CAPSULES_DETAIL_SUCCESS = 'GET_CAPSULES_DETAIL_SUCCESS';
export const GET_CAPSULES_DETAIL_FAIL = 'GET_CAPSULES_DETAIL_FAIL';

export const GET_CAPSULES_UPCOMING = 'GET_CAPSULES_UPCOMING';
export const GET_CAPSULES_UPCOMING_SUCCESS = 'GET_CAPSULES_UPCOMING_SUCCESS';
export const GET_CAPSULES_UPCOMING_FAIL = 'GET_CAPSULES_UPCOMING_FAIL';

export const GET_CAPSULES_PAST = 'GET_CAPSULES_PAST';
export const GET_CAPSULES_PAST_SUCCESS = 'GET_CAPSULES_PAST_SUCCESS';
export const GET_CAPSULES_PAST_FAIL = 'GET_CAPSULES_PAST_FAIL';
// Capsules //


// Cores //
export const GET_ALL_CORES = 'GET_ALL_CORES';
export const GET_CORES_SUCCESS = 'GET_CORES_SUCCESS';
export const GET_CORES_FAIL = 'GET_CORES_FAIL';

export const GET_CORES_DETAIL = 'GET_CORES_DETAIL';
export const GET_CORES_DETAIL_SUCCESS = 'GET_CORES_DETAIL_SUCCESS';
export const GET_CORES_DETAIL_FAIL = 'GET_CORES_DETAIL_FAIL';

export const GET_CORES_UPCOMING = 'GET_CORES_UPCOMING';
export const GET_CORES_UPCOMING_SUCCESS = 'GET_CORES_UPCOMING_SUCCESS';
export const GET_CORES_UPCOMING_FAIL = 'GET_CORES_UPCOMING_FAIL';

export const GET_CORES_PAST = 'GET_CORES_PAST';
export const GET_CORES_PAST_SUCCESS = 'GET_CORES_PAST_SUCCESS';
export const GET_CORES_PAST_FAIL = 'GET_CORES_PAST_FAIL';
// Cores //


// Dragons //
export const GET_ALL_DRAGONS = 'GET_ALL_DRAGONS';
export const GET_DRAGONS_SUCCESS = 'GET_DRAGONS_SUCCESS';
export const GET_DRAGONS_FAIL = 'GET_DRAGONS_FAIL';

export const GET_DRAGONS_DETAIL = 'GET_DRAGONS_DETAIL';
export const GET_DRAGONS_DETAIL_SUCCESS = 'GET_DRAGONS_DETAIL_SUCCESS';
export const GET_DRAGONS_DETAIL_FAIL = 'GET_DRAGONS_DETAIL_FAIL';
// Dragons //

// History //
export const GET_ALL_HISTORY = 'GET_ALL_HISTORY';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAIL = 'GET_HISTORY_FAIL';

export const GET_HISTORY_DETAIL = 'GET_HISTORY_DETAIL';
export const GET_HISTORY_DETAIL_SUCCESS = 'GET_HISTORY_DETAIL_SUCCESS';
export const GET_HISTORY_DETAIL_FAIL = 'GET_HISTORY_DETAIL_FAIL';
// History //

// Info //
export const GET_COMPANY_INFO = 'GET_COMPANY_INFO';
export const GET_COMPANY_INFO_SUCCESS = 'GET_COMPANY_INFO_SUCCESS';
export const GET_COMPANY_INFO_FAIL = 'GET_COMPANY_INFO_FAIL';

export const GET_INFO = 'GET_INFO';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';
// Info //


// Launch Pad //
export const GET_ALL_LAUNCHPAD = 'GET_ALL_LAUNCHPAD';
export const GET_LAUNCHPAD_SUCCESS = 'GET_LAUNCHPAD_SUCCESS';
export const GET_LAUNCHPAD_FAIL = 'GET_LAUNCHPAD_FAIL';

export const GET_LAUNCHPAD_DETAIL = 'GET_LAUNCHPAD_DETAIL';
export const GET_LAUNCHPAD_DETAIL_SUCCESS = 'GET_LAUNCHPAD_DETAIL_SUCCESS';
export const GET_LAUNCHPAD_DETAIL_FAIL = 'GET_LAUNCHPAD_DETAIL_FAIL';
// Launch Pad //

// Land Pad //
export const GET_ALL_LANDPAD = 'GET_ALL_LANDPAD';
export const GET_LANDPAD_SUCCESS = 'GET_LANDPAD_SUCCESS';
export const GET_LANDPAD_FAIL = 'GET_LANDPAD_FAIL';

export const GET_LANDPAD_DETAIL = 'GET_LANDPAD_DETAIL';
export const GET_LANDPAD_DETAIL_SUCCESS = 'GET_LANDPAD_DETAIL_SUCCESS';
export const GET_LANDPAD_DETAIL_FAIL = 'GET_LANDPAD_DETAIL_FAIL';
// Land Pad //

// Capsules //
export const GET_ALL_LAUNCHES = 'GET_ALL_LAUNCHES';
export const GET_LAUNCHES_SUCCESS = 'GET_LAUNCHES_SUCCESS';
export const GET_LAUNCHES_FAIL = 'GET_LAUNCHES_FAIL';

export const GET_LAUNCHES_DETAIL = 'GET_LAUNCHES_DETAIL';
export const GET_LAUNCHES_DETAIL_SUCCESS = 'GET_LAUNCHES_DETAIL_SUCCESS';
export const GET_LAUNCHES_DETAIL_FAIL = 'GET_LAUNCHES_DETAIL_FAIL';

export const GET_LAUNCHES_UPCOMING = 'GET_LAUNCHES_UPCOMING';
export const GET_LAUNCHES_UPCOMING_SUCCESS = 'GET_LAUNCHES_UPCOMING_SUCCESS';
export const GET_LAUNCHES_UPCOMING_FAIL = 'GET_LAUNCHES_UPCOMING_FAIL';

export const GET_LAUNCHES_PAST = 'GET_LAUNCHES_PAST';
export const GET_LAUNCHES_PAST_SUCCESS = 'GET_LAUNCHES_PAST_SUCCESS';
export const GET_LAUNCHES_PAST_FAIL = 'GET_LAUNCHES_PAST_FAIL';
// Capsules //